/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst";
export {};
declare module "sst" {
  export interface Resource {
    AuthSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
    Database: {
      database: string;
      host: string;
      password: string;
      port: number;
      type: "sst.aws.Postgres";
      username: string;
    };
    GoogleClientId: {
      type: "sst.sst.Secret";
      value: string;
    };
    GoogleClientSecret: {
      type: "sst.sst.Secret";
      value: string;
    };
  }
}
